spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:mysql://localhost:3306/ ?serverTimezone=UTC"
  jpa:
    show-sql: true
    hibernate:
      naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
